- CHANGELOG.md
- csm_api_client/service/gateway.py
- pyproject.toml
This change fixes the type signature of the set_timeout() method so that it permits `None` to be passed. This allows `None` to be used for the `timeout` parameter for `requests.request()`, which does not time out requests after a time limit.
* Resolves [CRAYSAT-1593](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1593)
Run type checker on SAT codebase after updating `csm-api-client` builds.
None - no functionality changing
> CRAYSAT-1593: Fix set_timeout() type signature

- Jenkinsfile.github
This commit adds creation of a .netrc file on the Jenkins host on which the build is running. The intention of this file is to provide credential authentication in the case when the package's dependencies are being installed in a VirtualEnv on the host to facilitate running unit tests. This uses the utility jenkinsUtils.writeNetRc() found in csm-shared-library.
Test Description: Built package in Jenkins
> CRAYSAT-1620: Use authentication when accessing csm-python-modules

- CHANGELOG.md
- csm_api_client/service/gateway.py
- tests/service/test_gateway.py
The `_make_req` method was dropping the `json` kwarg when making the request, which caused calls to the `patch` method that used the `json` keyword argument to fail.
* Resolves [CRAYSAT-1650](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1650)
* frigg
Unit tests pass. Manually made this change in a `sat bash` container image and verified that the image renaming step in `sat bootprep` was working again.
Low risk.
> CRAYSAT-1650: Fix patch method of APIGatewayClient

- pyproject.toml
This version is actually what controls the version of the package published to artifactory.
Ran `./build_scripts/build.sh python_package` to make sure the 1.1.1 version was built.
> CRAYSAT-1650: Fix version in `pyproject.toml`

- CHANGELOG.md
- csm_api_client/session.py
- pyproject.toml
- tests/test_session.py
This change fixes the way tokens are handled when a new token is being fetched. Previously when a token file didn't already exist for a token, a new token would be fetched but not saved, and subsequent API calls could not use the token.
* Resolves [CRAYSAT-1678](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1678)
* `frigg`
Run unit tests. Test `sat auth` with empty config directory to ensure that new tokens can be created.
> CRAYSAT-1678: Fix token fetch during authentication

- .github/workflows/license-check.yaml
- CHANGELOG.md
- csm_api_client/service/cfs.py
- pyproject.toml
- tests/service/test_cfs.py
The name scheme for CFS image customization containers has been changed such that Ansible containers no longer have a numeric suffix. As a result, the 'teardown' container was being recommended as the suggested container from which to view logs. This is incorrect for customization jobs where the 'ansible' container fails.
* Resolves [CRAYSAT-1673](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1673)/[CASMTRIAGE-4983](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4983)
* `gamora`
Run unit tests. Run test with mock bootprep file with barebones image and failing CFS configuration; confirm that the correct ansible container is selected as the debug container.
> CRAYSAT-1673: Update CFS container ordering logic

- .github/workflows/backport.yml
The license-check workflow wants this file to have current copyright year when we try to merge main to release/1.1.
> CRAYSAT-1750: Update backport copyright to satisfy license-check

- CHANGELOG.md
- csm_api_client/service/cfs.py
- pyproject.toml
- tests/service/test_cfs.py
* CASMINST-6597: Declare version 1.2.0 of csm-api-client
Update the changelog and declare a new version in `pyproject.toml`.
* CASMINST-6597: Add methods to CFSClient to support cfs-config-util
Add a couple methods to the `CFSClient` class to support functionality
needed by `cfs-config-util`.
Add a method `get_component_ids_using_config` that gets a list of the
CFS component IDs for all components that have the given CFS
configuration assigned as their `desiredConfig`.
Add a method `update_component` that updates a CFS component based on
the given parameters.
Test Description:
New unit tests are passing.
Tested manually on my macbook in a Python virtual environment with the
`sat` package and this version of `csm_api_client` installed. Created a
`CFSClient` with `CFSClient(SATSession())` …
> CASMINST-6597: Add additional CFS client functionality

- CHANGELOG.md
- csm_api_client/service/cfs.py
- pyproject.toml
IM:CRAYSAT-1747
Reviewer: Ryan
Incorrect logging is observed in sat bootprep logs SAT is also generating a session name, which is conflicting with session name generated in create_image_customization_session
Hence 2 session names are observed in log, leading to confusion
Allowing to pass a CFS session name from sat to cfs.py as this would allow in maintaining consistency with logging.
* Resolves [CRAYSAT-1747](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1747)
baldar
Tested on baldar
validated the sat bootprep with single layer yaml file to verify if the same session name is reflected in the logging
Minimal
> CRAYSAT-1747:Allow passing CFS session name

- .github/workflows/license-check.yaml
- CHANGELOG.md
- csm_api_client/service/cfs.py
- pyproject.toml
Merge main to release/1.2 to get a stable build of the latest 1.2.1
This will be merged locally and pushed to get a true fastforward merge without a merge commit, which git does not allow through the pull request web UI
* [CRAYSAT-1747](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1747)
* [CRAYSAT-1796](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1796)
See PR's to main
See PR's to main
> Update release/1.2 to 1.2.1

- csm_api_client/service/cfs.py
- tests/service/test_cfs.py
Improve upon unit test for `_update_container_status` method as follows:
* Separate tests into their own class since they are different enough from other existing TestCase class.
* Add more thoroughly mocked out container status data in the `setUp` method.
* Add a unit test that tests the "happy path" through the method and asserts against the info-level log messages.
* Add more assertions on the log messages logged in the various scenarios when the `init_container_statuses` and/or `container_statuses` are `None`.
* Part of CRAYSAT-1775
Unit tests pass.
Low risk unit test improvements.
> CRAYSAT-1775: Improve upon `_update_container_status` tests

- CHANGELOG.md
- csm_api_client/service/cfs.py
- pyproject.toml
- tests/service/test_cfs.py
IM:CRAYSAT-1775
Reviewer:Ryan
Update the _update_container_status method when either init_container_statuses or container_statuses or both are None._
_If they are None we can log an info message and will skip processing the container statuses until they are populated._
_Resolves [CRAYSAT-1775](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1775)_
TO DO
TO DO
_Minimal_
> CRAYSAT-1775:Update container status when it is None

- CHANGELOG.md
- pyproject.toml
The kubernetes package version constraint was requiring too new of a version of kuberenetes. When this library is used by a version of sat for CSM 1.5, we want to use a 22.y.z version of the kubernetes package to match the 1.22 version of the Kubernetes cluster. When used by a version of sat for CSM 1.6, we want to use a 23.y.z version of the kubernetes package to match the 1.23 version of the Kubernetes cluster.
Relax the constraint to just require version 22 or newer. The lock file can stay the same as it's not used when this package is included as a dependency.
* Resolves CRAYSAT-1848
* The sat repo will be updated to use this new version
* odin
Built a new cray-sat container image using this unstable version. In a Python interpreter in the cray-sat container, tested as follows:
``` …
```
> CRAYSAT-1848: Fix kubernetes version constraint

- CHANGELOG.md
- poetry.lock
- pyproject.toml
Reviewer:Ryan
Updating the cray-product-catalogue to latest version that handles the split Kubernetes ConfigMap.
* Resolves [CRAYSAT-1884](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1884)
yet to be tested
minimal
> CRAYSAT-1884: Updating the cray-product-catalogue to 2.3.1

- CHANGELOG.md
- poetry.lock
- pyproject.toml
Hash value of the cray-product-catalog wasnt getting updated to the latest value of the build in the source(artifactory)
Hence updated the poetry.lock file by updating it.
Build failure link: https://jenkins.algol60.net/blue/organizations/jenkins/Cray-HPE%2Fpython-csm-api-client/detail/CRAYSAT-1840-cfs-client-v3/14/pipeline/
* Resolves [CRAYSAT-1898](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1898)
* Resolves build issue observed in https://github.com/Cray-HPE/python-csm-api-client/pull/33
* The build got passed without any issues in the pipeline.
minimal
> CRAYSAT-1898:Fixing poetry lock file issue

- CHANGELOG.md
- csm_api_client/service/cfs.py
- csm_api_client/service/gateway.py
- csm_api_client/util.py
- pyproject.toml
- tests/service/test_cfs.py
- tests/service/test_gateway.py
- tests/test_util.py
* CRAYSAT-1840: Add support for CFS v3 API
Add support for the CFS v3 API while preserving support for the CFS v2
API. This is accomplished by making CFS-API-version specific versions of
several of the classes in the `cfs` module. For backwards compatibility,
the existing unversioned class names, `CFSConfiguration`.
`CFSConfigurationLayer`, and `CFSClient` are now aliases for the
`CFSV2Configuration`, `CFSV2ConfigurationLayer`, and `CFSV2Client`
classes.
The `CFSImageConfigurationSession` class is still used for both CFS v2
and v3 since there were no large changes required, and it could be
easily generalized to both CFS API versions.
As much as possible, functionality that is common between CFS v2 and v3
is implemented in common abstract base classes which are inherited for
creating the …
> CRAYSAT-1840: Add support for CFS v3 API

- CHANGELOG.md
- poetry.lock
- pyproject.toml
updating poetry lock file to get latest hash values to fix the build issue
* Resolves [CRAYSAT-1901](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1901)
Backport of https://github.com/Cray-HPE/python-csm-api-client/pull/36
Build has passed without any issues
minimal
> CRAYSAT-1901: updating poetry lock file to get latest hash values

- CHANGELOG.md
- build_scripts/build.sh
- csm_api_client/service/vcs.py
- poetry.lock
- pyproject.toml
_update-cfs-config and prepare-images stage is failing after hanging during CSM only upgrade using IUF_
_It hangs up when its executing the command "git ls-remote https://crayvcs@api-gw-service-nmn.local/vcs/cray/uss-config-management.git "_
_Tried fetching the credentials from container if present else kubernetes which doesn't get hungs up for long time_
_Resolves [CASMTRIAGE-7272](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7272)_
fanta
_Tested with IUF which is working without hangs up_
_Minimal_
> CASMTRIAGE-7272: update-cfs-config and prepare-images stage is failing after hanging during CSM only upgrade using IUF

- CHANGELOG.md
- build_scripts/build.sh
- csm_api_client/service/vcs.py
- poetry.lock
- pyproject.toml
Backport csm-api-client to 2.2.2
_update-cfs-config and prepare-images stage is failing after hanging during CSM only upgrade using IUF_
_It hangs up when its executing the command "git ls-remote https://crayvcs@api-gw-service-nmn.local/vcs/cray/uss-config-management.git "_
_Tried fetching the credentials from container if present else kubernetes which doesn't get hungs up for long time_
_Resolves [CASMTRIAGE-7272](https://jira-pro.it.hpe.com:8443/browse/CASMTRIAGE-7272): https://github.com/Cray-HPE/python-csm-api-client/pull/40_
_See the linked PR_
_See the linked PR_
> CASMTRIAGE-7272: Backport csm-api-client to 2.2.2

- CHANGELOG.md
- csm_api_client/service/vcs.py
- poetry.lock
- pyproject.toml
_Remove the ability to read VCS password from a file which is no longer necessary._
_Resolves [CRAYSAT-1913](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1913)._
Yet to be tested on the system where it upgrades from CSM 1.5.x to 1.6.1
_Since we didn't get system to test the changes when CSM upgrade from 1.5.x to 1.6.0,  Test this on update-cfs-config stage and prepare images stage when upgrading from CSM 1.5.x to 1.6.1 in future_
_Risk is low as we are removing only the code redundancy_
> CRAYSAT-1913: Remove the ability to read VCS password from a file

- CHANGELOG.md
- poetry.lock
- pyproject.toml
_Update the poetry lock file with `cray product catalog` version to 2.5.0 where it maintained the hash consistency_
* Resolves [CRAYSAT-1921](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1921)
_We updated only `poetry.lock` with latest `cray-product-catalog` version with consistent hash values._
_The build passed successfully after changes_
_Low_
> CRAYSAT-1925: Update cpc with hash in poetry lock to maintain consistency

- CHANGELOG.md
- poetry.lock
- pyproject.toml
_Backport `csm_api_client` to `2.2.4`_
* Resolves [CRAYSAT-1921](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1921): https://github.com/Cray-HPE/python-csm-api-client/pull/45
_See linked PR._
_See linked PR_
> CRAYSAT-1925: Backport  Update cpc with hash in poetry lock to maintain consistency

- CHANGELOG.md
- csm_api_client/service/cfs.py
- pyproject.toml
- tests/service/test_cfs.py
Fix the `req_payload` property of the `CFSLayerBase` class to include values even when they are `False` (or Falsey). This ensures that the `ims_require_dkms` parameter is included in the request payload, even when set to `False`.
Add a unit test for this scenario.
* Resolves CRAYSAT-1896
* rocket
Included in a build of `cray-sat` and tested by creating a CFS configuration containing both true and false values for `ims_require_dkms`.
This is pretty low-risk. It's just ensuring False values get included in CFS API requests.
> CRAYSAT-1896: Fix `CFSLayerBase.req_payload` to include False values

- CHANGELOG.md
- csm_api_client/session.py
- pyproject.toml
add error logging when unable to find token file path and unwrap ~ as home directory
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_
* Resolves [CRAYSAT-1649](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1649)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after https://github.com/Cray-HPE/sat/pull/293
* Rocket
* Drax
_Are there known issues with these changes? Any other special considerations?_ …
> CRAYSAT-1649: add error logging when unable to find token file path

- CHANGELOG.md
- csm_api_client/service/cfs.py
- pyproject.toml
_Stop resolving branch names to commit hashes from `sat bootprep` in cfs v3. Use `drop_branches` parameter supported by cfs for v3_
* Resolves [CRAYSAT-1784](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1784)
_Will test from sat using unstable build_
_Min_
> CRAYSAT-1784: Support for `drop_branches` in CFS v3

- CHANGELOG.md
- csm_api_client/service/cfs.py
- pyproject.toml
_Add support for specifying a CFS configuration layer using the `source` property instead of a `clone_url`._
* Resolves [CRAYSAT-1969](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1969)
_Will test from sat using unstable build._
_Risk is only in creating the sources but the credentials are confidential since it stores in a vault_
> CRAYSAT-1969: Add source property to cfsv3

- CHANGELOG.md
- csm_api_client/service/cfs.py
- pyproject.toml
_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_
_Support `debug-on-failure` of cfs v3 in `sat bootprep`_
* Resolves [CRAYSAT-1991](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1991)
_See in https://github.com/Cray-HPE/sat/pull/346._
_Low_
> CRAYSAT-1991: Support `debug_on_failure` of CFS V3
